"""Concatenate the SQL sources into one paste-able file.

Running three files in the Supabase SQL editor is awkward on a phone, so this
builds supabase/setup.sql — schema + policies + seed, in order, in one paste.

Re-run after editing any of the three:  python tools/build_setup_sql.py
"""

import pathlib

SOURCES = ("schema.sql", "maintenance.sql", "policies.sql", "seed.sql")
OUT = pathlib.Path("supabase/setup.sql")

header = """-- Grant Household Inventory — complete setup, in one paste.
--
-- Supabase dashboard -> SQL Editor -> New query -> paste all of this -> Run.
-- Safe to re-run; it is schema.sql + policies.sql + seed.sql concatenated.
-- Generated by tools/build_setup_sql.py — edit the three sources, not this file.

"""

parts = []
for name in SOURCES:
    body = pathlib.Path("supabase", name).read_text(encoding="utf-8").strip()
    bar = "=" * 68
    parts.append(f"-- {bar}\n-- {name}\n-- {bar}\n\n{body}\n")

text = header + "\n\n".join(parts)
text += "\nselect 'Grant Household Inventory schema installed.' as status;\n"
OUT.write_text(text, encoding="utf-8")
print(f"{OUT}: {len(text.splitlines())} lines")
